syntax = "proto3";

package berth.ml.v1;

option go_package = "github.com/AyushCN/berth/proto/gen/go/ml/v1";

service Predictor {
  rpc Predict(PredictRequest) returns (PredictResponse);
}

message PredictRequest {
  string git_url = 1;
  string local_path = 2;
  string branch = 3;
}

message PredictResponse {
  RuntimeProfile profile = 1;
}

message RuntimeProfile {
  string language = 1;
  string base_image = 2;
  string install_cmd = 3;
  string start_cmd = 4;
  int32 port = 5;
  bool needs_db = 6;
  double confidence = 7;
}
