// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: additional.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSandboxesByOwner = `-- name: CountSandboxesByOwner :one
SELECT COUNT(*) FROM sandboxes WHERE owner_id = $1
`

func (q *Queries) CountSandboxesByOwner(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSandboxesByOwner, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listSandboxesByOwner = `-- name: ListSandboxesByOwner :many
SELECT id, project_id, owner_id, name, git_url, git_branch, state, runtime_language, runtime_base_image, runtime_port, needs_db, container_id, public_url, created_at, updated_at, expires_at FROM sandboxes WHERE owner_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSandboxesByOwner(ctx context.Context, ownerID uuid.UUID) ([]Sandbox, error) {
	rows, err := q.db.Query(ctx, listSandboxesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sandbox{}
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.OwnerID,
			&i.Name,
			&i.GitUrl,
			&i.GitBranch,
			&i.State,
			&i.RuntimeLanguage,
			&i.RuntimeBaseImage,
			&i.RuntimePort,
			&i.NeedsDb,
			&i.ContainerID,
			&i.PublicUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContainerID = `-- name: UpdateContainerID :exec
UPDATE sandboxes SET container_id = $2, updated_at = NOW() WHERE id = $1
`

type UpdateContainerIDParams struct {
	ID          uuid.UUID   `json:"id"`
	ContainerID pgtype.Text `json:"container_id"`
}

func (q *Queries) UpdateContainerID(ctx context.Context, arg UpdateContainerIDParams) error {
	_, err := q.db.Exec(ctx, updateContainerID, arg.ID, arg.ContainerID)
	return err
}

const updateUserToken = `-- name: UpdateUserToken :exec
UPDATE users SET github_token_encrypted = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserTokenParams struct {
	ID                   uuid.UUID   `json:"id"`
	GithubTokenEncrypted pgtype.Text `json:"github_token_encrypted"`
}

func (q *Queries) UpdateUserToken(ctx context.Context, arg UpdateUserTokenParams) error {
	_, err := q.db.Exec(ctx, updateUserToken, arg.ID, arg.GithubTokenEncrypted)
	return err
}
