// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: additional.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const updateUserToken = `-- name: UpdateUserToken :exec
UPDATE users SET github_token_encrypted = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserTokenParams struct {
	ID                   uuid.UUID   `json:"id"`
	GithubTokenEncrypted pgtype.Text `json:"github_token_encrypted"`
}

func (q *Queries) UpdateUserToken(ctx context.Context, arg UpdateUserTokenParams) error {
	_, err := q.db.Exec(ctx, updateUserToken, arg.ID, arg.GithubTokenEncrypted)
	return err
}
