// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: build.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBuild = `-- name: CreateBuild :one
INSERT INTO builds (
    build_plan_id, workspace_id, commit_hash, status
) VALUES (
    $1, $2, $3, $4
) RETURNING id, build_plan_id, workspace_id, commit_hash, status, image_id, logs, started_at, finished_at, error, cache_hit, build_duration_ms, created_at
`

type CreateBuildParams struct {
	BuildPlanID uuid.UUID `json:"build_plan_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	CommitHash  string    `json:"commit_hash"`
	Status      string    `json:"status"`
}

func (q *Queries) CreateBuild(ctx context.Context, arg CreateBuildParams) (Build, error) {
	row := q.db.QueryRow(ctx, createBuild,
		arg.BuildPlanID,
		arg.WorkspaceID,
		arg.CommitHash,
		arg.Status,
	)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.BuildPlanID,
		&i.WorkspaceID,
		&i.CommitHash,
		&i.Status,
		&i.ImageID,
		&i.Logs,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
		&i.CacheHit,
		&i.BuildDurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const createBuildPlan = `-- name: CreateBuildPlan :one
INSERT INTO build_plans (
    runtime_profile_id, base_image, dockerfile, build_args,
    install_command, build_command, start_command, working_dir,
    port, confidence, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, runtime_profile_id, base_image, dockerfile, build_args, install_command, build_command, start_command, working_dir, port, confidence, status, error, created_at, updated_at
`

type CreateBuildPlanParams struct {
	RuntimeProfileID uuid.UUID   `json:"runtime_profile_id"`
	BaseImage        string      `json:"base_image"`
	Dockerfile       string      `json:"dockerfile"`
	BuildArgs        []byte      `json:"build_args"`
	InstallCommand   pgtype.Text `json:"install_command"`
	BuildCommand     pgtype.Text `json:"build_command"`
	StartCommand     pgtype.Text `json:"start_command"`
	WorkingDir       pgtype.Text `json:"working_dir"`
	Port             pgtype.Int4 `json:"port"`
	Confidence       float32     `json:"confidence"`
	Status           string      `json:"status"`
}

func (q *Queries) CreateBuildPlan(ctx context.Context, arg CreateBuildPlanParams) (BuildPlan, error) {
	row := q.db.QueryRow(ctx, createBuildPlan,
		arg.RuntimeProfileID,
		arg.BaseImage,
		arg.Dockerfile,
		arg.BuildArgs,
		arg.InstallCommand,
		arg.BuildCommand,
		arg.StartCommand,
		arg.WorkingDir,
		arg.Port,
		arg.Confidence,
		arg.Status,
	)
	var i BuildPlan
	err := row.Scan(
		&i.ID,
		&i.RuntimeProfileID,
		&i.BaseImage,
		&i.Dockerfile,
		&i.BuildArgs,
		&i.InstallCommand,
		&i.BuildCommand,
		&i.StartCommand,
		&i.WorkingDir,
		&i.Port,
		&i.Confidence,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createImage = `-- name: CreateImage :one
INSERT INTO images (
    build_id, workspace_id, tag, digest, size_bytes, base_image, labels
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, build_id, workspace_id, tag, digest, size_bytes, base_image, labels, created_at, last_used_at
`

type CreateImageParams struct {
	BuildID     pgtype.UUID `json:"build_id"`
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	Tag         string      `json:"tag"`
	Digest      pgtype.Text `json:"digest"`
	SizeBytes   pgtype.Int8 `json:"size_bytes"`
	BaseImage   pgtype.Text `json:"base_image"`
	Labels      []byte      `json:"labels"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, createImage,
		arg.BuildID,
		arg.WorkspaceID,
		arg.Tag,
		arg.Digest,
		arg.SizeBytes,
		arg.BaseImage,
		arg.Labels,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.BuildID,
		&i.WorkspaceID,
		&i.Tag,
		&i.Digest,
		&i.SizeBytes,
		&i.BaseImage,
		&i.Labels,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteBuild = `-- name: DeleteBuild :exec
DELETE FROM builds WHERE id = $1
`

func (q *Queries) DeleteBuild(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBuild, id)
	return err
}

const deleteBuildPlan = `-- name: DeleteBuildPlan :exec
DELETE FROM build_plans WHERE id = $1
`

func (q *Queries) DeleteBuildPlan(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBuildPlan, id)
	return err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM images WHERE id = $1
`

func (q *Queries) DeleteImage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteImage, id)
	return err
}

const getBuild = `-- name: GetBuild :one
SELECT id, build_plan_id, workspace_id, commit_hash, status, image_id, logs, started_at, finished_at, error, cache_hit, build_duration_ms, created_at FROM builds WHERE id = $1
`

func (q *Queries) GetBuild(ctx context.Context, id uuid.UUID) (Build, error) {
	row := q.db.QueryRow(ctx, getBuild, id)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.BuildPlanID,
		&i.WorkspaceID,
		&i.CommitHash,
		&i.Status,
		&i.ImageID,
		&i.Logs,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
		&i.CacheHit,
		&i.BuildDurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const getBuildPlan = `-- name: GetBuildPlan :one
SELECT id, runtime_profile_id, base_image, dockerfile, build_args, install_command, build_command, start_command, working_dir, port, confidence, status, error, created_at, updated_at FROM build_plans WHERE id = $1
`

func (q *Queries) GetBuildPlan(ctx context.Context, id uuid.UUID) (BuildPlan, error) {
	row := q.db.QueryRow(ctx, getBuildPlan, id)
	var i BuildPlan
	err := row.Scan(
		&i.ID,
		&i.RuntimeProfileID,
		&i.BaseImage,
		&i.Dockerfile,
		&i.BuildArgs,
		&i.InstallCommand,
		&i.BuildCommand,
		&i.StartCommand,
		&i.WorkingDir,
		&i.Port,
		&i.Confidence,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBuildPlanByRuntimeProfile = `-- name: GetBuildPlanByRuntimeProfile :one
SELECT id, runtime_profile_id, base_image, dockerfile, build_args, install_command, build_command, start_command, working_dir, port, confidence, status, error, created_at, updated_at FROM build_plans WHERE runtime_profile_id = $1
`

func (q *Queries) GetBuildPlanByRuntimeProfile(ctx context.Context, runtimeProfileID uuid.UUID) (BuildPlan, error) {
	row := q.db.QueryRow(ctx, getBuildPlanByRuntimeProfile, runtimeProfileID)
	var i BuildPlan
	err := row.Scan(
		&i.ID,
		&i.RuntimeProfileID,
		&i.BaseImage,
		&i.Dockerfile,
		&i.BuildArgs,
		&i.InstallCommand,
		&i.BuildCommand,
		&i.StartCommand,
		&i.WorkingDir,
		&i.Port,
		&i.Confidence,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBuildsByBuildPlan = `-- name: GetBuildsByBuildPlan :many
SELECT id, build_plan_id, workspace_id, commit_hash, status, image_id, logs, started_at, finished_at, error, cache_hit, build_duration_ms, created_at FROM builds 
WHERE build_plan_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetBuildsByBuildPlan(ctx context.Context, buildPlanID uuid.UUID) ([]Build, error) {
	rows, err := q.db.Query(ctx, getBuildsByBuildPlan, buildPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Build{}
	for rows.Next() {
		var i Build
		if err := rows.Scan(
			&i.ID,
			&i.BuildPlanID,
			&i.WorkspaceID,
			&i.CommitHash,
			&i.Status,
			&i.ImageID,
			&i.Logs,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Error,
			&i.CacheHit,
			&i.BuildDurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBuildsByWorkspace = `-- name: GetBuildsByWorkspace :many
SELECT id, build_plan_id, workspace_id, commit_hash, status, image_id, logs, started_at, finished_at, error, cache_hit, build_duration_ms, created_at FROM builds 
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetBuildsByWorkspaceParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) GetBuildsByWorkspace(ctx context.Context, arg GetBuildsByWorkspaceParams) ([]Build, error) {
	rows, err := q.db.Query(ctx, getBuildsByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Build{}
	for rows.Next() {
		var i Build
		if err := rows.Scan(
			&i.ID,
			&i.BuildPlanID,
			&i.WorkspaceID,
			&i.CommitHash,
			&i.Status,
			&i.ImageID,
			&i.Logs,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Error,
			&i.CacheHit,
			&i.BuildDurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImage = `-- name: GetImage :one
SELECT id, build_id, workspace_id, tag, digest, size_bytes, base_image, labels, created_at, last_used_at FROM images WHERE id = $1
`

func (q *Queries) GetImage(ctx context.Context, id uuid.UUID) (Image, error) {
	row := q.db.QueryRow(ctx, getImage, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.BuildID,
		&i.WorkspaceID,
		&i.Tag,
		&i.Digest,
		&i.SizeBytes,
		&i.BaseImage,
		&i.Labels,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getImageByTag = `-- name: GetImageByTag :one
SELECT id, build_id, workspace_id, tag, digest, size_bytes, base_image, labels, created_at, last_used_at FROM images WHERE tag = $1
`

func (q *Queries) GetImageByTag(ctx context.Context, tag string) (Image, error) {
	row := q.db.QueryRow(ctx, getImageByTag, tag)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.BuildID,
		&i.WorkspaceID,
		&i.Tag,
		&i.Digest,
		&i.SizeBytes,
		&i.BaseImage,
		&i.Labels,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getImagesByWorkspace = `-- name: GetImagesByWorkspace :many
SELECT id, build_id, workspace_id, tag, digest, size_bytes, base_image, labels, created_at, last_used_at FROM images 
WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetImagesByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]Image, error) {
	rows, err := q.db.Query(ctx, getImagesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.BuildID,
			&i.WorkspaceID,
			&i.Tag,
			&i.Digest,
			&i.SizeBytes,
			&i.BaseImage,
			&i.Labels,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestBuildByWorkspace = `-- name: GetLatestBuildByWorkspace :one
SELECT id, build_plan_id, workspace_id, commit_hash, status, image_id, logs, started_at, finished_at, error, cache_hit, build_duration_ms, created_at FROM builds 
WHERE workspace_id = $1
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestBuildByWorkspace(ctx context.Context, workspaceID uuid.UUID) (Build, error) {
	row := q.db.QueryRow(ctx, getLatestBuildByWorkspace, workspaceID)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.BuildPlanID,
		&i.WorkspaceID,
		&i.CommitHash,
		&i.Status,
		&i.ImageID,
		&i.Logs,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
		&i.CacheHit,
		&i.BuildDurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const updateBuild = `-- name: UpdateBuild :one
UPDATE builds SET
    status = COALESCE($2, status),
    image_id = COALESCE($3, image_id),
    logs = COALESCE($4, logs),
    started_at = COALESCE($5, started_at),
    finished_at = COALESCE($6, finished_at),
    error = COALESCE($7, error),
    cache_hit = COALESCE($8, cache_hit),
    build_duration_ms = COALESCE($9, build_duration_ms)
WHERE id = $1
RETURNING id, build_plan_id, workspace_id, commit_hash, status, image_id, logs, started_at, finished_at, error, cache_hit, build_duration_ms, created_at
`

type UpdateBuildParams struct {
	ID              uuid.UUID          `json:"id"`
	Status          pgtype.Text        `json:"status"`
	ImageID         pgtype.UUID        `json:"image_id"`
	Logs            pgtype.Text        `json:"logs"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
	Error           pgtype.Text        `json:"error"`
	CacheHit        pgtype.Bool        `json:"cache_hit"`
	BuildDurationMs pgtype.Int8        `json:"build_duration_ms"`
}

func (q *Queries) UpdateBuild(ctx context.Context, arg UpdateBuildParams) (Build, error) {
	row := q.db.QueryRow(ctx, updateBuild,
		arg.ID,
		arg.Status,
		arg.ImageID,
		arg.Logs,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Error,
		arg.CacheHit,
		arg.BuildDurationMs,
	)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.BuildPlanID,
		&i.WorkspaceID,
		&i.CommitHash,
		&i.Status,
		&i.ImageID,
		&i.Logs,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
		&i.CacheHit,
		&i.BuildDurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const updateBuildPlan = `-- name: UpdateBuildPlan :one
UPDATE build_plans SET
    base_image = COALESCE($2, base_image),
    dockerfile = COALESCE($3, dockerfile),
    build_args = COALESCE($4, build_args),
    install_command = COALESCE($5, install_command),
    build_command = COALESCE($6, build_command),
    start_command = COALESCE($7, start_command),
    working_dir = COALESCE($8, working_dir),
    port = COALESCE($9, port),
    confidence = COALESCE($10, confidence),
    status = COALESCE($11, status),
    error = COALESCE($12, error),
    updated_at = NOW()
WHERE id = $1
RETURNING id, runtime_profile_id, base_image, dockerfile, build_args, install_command, build_command, start_command, working_dir, port, confidence, status, error, created_at, updated_at
`

type UpdateBuildPlanParams struct {
	ID             uuid.UUID     `json:"id"`
	BaseImage      pgtype.Text   `json:"base_image"`
	Dockerfile     pgtype.Text   `json:"dockerfile"`
	BuildArgs      []byte        `json:"build_args"`
	InstallCommand pgtype.Text   `json:"install_command"`
	BuildCommand   pgtype.Text   `json:"build_command"`
	StartCommand   pgtype.Text   `json:"start_command"`
	WorkingDir     pgtype.Text   `json:"working_dir"`
	Port           pgtype.Int4   `json:"port"`
	Confidence     pgtype.Float4 `json:"confidence"`
	Status         pgtype.Text   `json:"status"`
	Error          pgtype.Text   `json:"error"`
}

func (q *Queries) UpdateBuildPlan(ctx context.Context, arg UpdateBuildPlanParams) (BuildPlan, error) {
	row := q.db.QueryRow(ctx, updateBuildPlan,
		arg.ID,
		arg.BaseImage,
		arg.Dockerfile,
		arg.BuildArgs,
		arg.InstallCommand,
		arg.BuildCommand,
		arg.StartCommand,
		arg.WorkingDir,
		arg.Port,
		arg.Confidence,
		arg.Status,
		arg.Error,
	)
	var i BuildPlan
	err := row.Scan(
		&i.ID,
		&i.RuntimeProfileID,
		&i.BaseImage,
		&i.Dockerfile,
		&i.BuildArgs,
		&i.InstallCommand,
		&i.BuildCommand,
		&i.StartCommand,
		&i.WorkingDir,
		&i.Port,
		&i.Confidence,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateImageLastUsed = `-- name: UpdateImageLastUsed :exec
UPDATE images SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateImageLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateImageLastUsed, id)
	return err
}
