// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: change_request.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createChangeRequest = `-- name: CreateChangeRequest :one
INSERT INTO change_requests (
    project_id, source_workspace_id, target_workspace_id,
    title, description, author_id, commits, files_changed
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, project_id, source_workspace_id, target_workspace_id, title, description, author_id, state, commits, files_changed, reviewer_id, reviewed_at, merged_at, merge_commit_hash, created_at, updated_at
`

type CreateChangeRequestParams struct {
	ProjectID         uuid.UUID   `json:"project_id"`
	SourceWorkspaceID uuid.UUID   `json:"source_workspace_id"`
	TargetWorkspaceID uuid.UUID   `json:"target_workspace_id"`
	Title             string      `json:"title"`
	Description       pgtype.Text `json:"description"`
	AuthorID          uuid.UUID   `json:"author_id"`
	Commits           []byte      `json:"commits"`
	FilesChanged      []byte      `json:"files_changed"`
}

func (q *Queries) CreateChangeRequest(ctx context.Context, arg CreateChangeRequestParams) (ChangeRequest, error) {
	row := q.db.QueryRow(ctx, createChangeRequest,
		arg.ProjectID,
		arg.SourceWorkspaceID,
		arg.TargetWorkspaceID,
		arg.Title,
		arg.Description,
		arg.AuthorID,
		arg.Commits,
		arg.FilesChanged,
	)
	var i ChangeRequest
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceWorkspaceID,
		&i.TargetWorkspaceID,
		&i.Title,
		&i.Description,
		&i.AuthorID,
		&i.State,
		&i.Commits,
		&i.FilesChanged,
		&i.ReviewerID,
		&i.ReviewedAt,
		&i.MergedAt,
		&i.MergeCommitHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChangeRequest = `-- name: DeleteChangeRequest :exec
DELETE FROM change_requests WHERE id = $1
`

func (q *Queries) DeleteChangeRequest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChangeRequest, id)
	return err
}

const getChangeRequest = `-- name: GetChangeRequest :one
SELECT cr.id, cr.project_id, cr.source_workspace_id, cr.target_workspace_id, cr.title, cr.description, cr.author_id, cr.state, cr.commits, cr.files_changed, cr.reviewer_id, cr.reviewed_at, cr.merged_at, cr.merge_commit_hash, cr.created_at, cr.updated_at, 
    sw.name as source_workspace_name,
    tw.name as target_workspace_name,
    u.username as author_username,
    u.avatar_url as author_avatar
FROM change_requests cr
JOIN workspaces sw ON cr.source_workspace_id = sw.id
JOIN workspaces tw ON cr.target_workspace_id = tw.id
JOIN users u ON cr.author_id = u.id
WHERE cr.id = $1
`

type GetChangeRequestRow struct {
	ID                  uuid.UUID          `json:"id"`
	ProjectID           uuid.UUID          `json:"project_id"`
	SourceWorkspaceID   uuid.UUID          `json:"source_workspace_id"`
	TargetWorkspaceID   uuid.UUID          `json:"target_workspace_id"`
	Title               string             `json:"title"`
	Description         pgtype.Text        `json:"description"`
	AuthorID            uuid.UUID          `json:"author_id"`
	State               string             `json:"state"`
	Commits             []byte             `json:"commits"`
	FilesChanged        []byte             `json:"files_changed"`
	ReviewerID          pgtype.UUID        `json:"reviewer_id"`
	ReviewedAt          pgtype.Timestamptz `json:"reviewed_at"`
	MergedAt            pgtype.Timestamptz `json:"merged_at"`
	MergeCommitHash     pgtype.Text        `json:"merge_commit_hash"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	SourceWorkspaceName string             `json:"source_workspace_name"`
	TargetWorkspaceName string             `json:"target_workspace_name"`
	AuthorUsername      pgtype.Text        `json:"author_username"`
	AuthorAvatar        pgtype.Text        `json:"author_avatar"`
}

func (q *Queries) GetChangeRequest(ctx context.Context, id uuid.UUID) (GetChangeRequestRow, error) {
	row := q.db.QueryRow(ctx, getChangeRequest, id)
	var i GetChangeRequestRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceWorkspaceID,
		&i.TargetWorkspaceID,
		&i.Title,
		&i.Description,
		&i.AuthorID,
		&i.State,
		&i.Commits,
		&i.FilesChanged,
		&i.ReviewerID,
		&i.ReviewedAt,
		&i.MergedAt,
		&i.MergeCommitHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceWorkspaceName,
		&i.TargetWorkspaceName,
		&i.AuthorUsername,
		&i.AuthorAvatar,
	)
	return i, err
}

const getChangeRequestsByProject = `-- name: GetChangeRequestsByProject :many
SELECT cr.id, cr.project_id, cr.source_workspace_id, cr.target_workspace_id, cr.title, cr.description, cr.author_id, cr.state, cr.commits, cr.files_changed, cr.reviewer_id, cr.reviewed_at, cr.merged_at, cr.merge_commit_hash, cr.created_at, cr.updated_at, 
    sw.name as source_workspace_name,
    tw.name as target_workspace_name,
    u.username as author_username,
    u.avatar_url as author_avatar,
    ru.username as reviewer_username
FROM change_requests cr
JOIN workspaces sw ON cr.source_workspace_id = sw.id
JOIN workspaces tw ON cr.target_workspace_id = tw.id
JOIN users u ON cr.author_id = u.id
LEFT JOIN users ru ON cr.reviewer_id = ru.id
WHERE cr.project_id = $1
ORDER BY cr.created_at DESC
LIMIT $2 OFFSET $3
`

type GetChangeRequestsByProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type GetChangeRequestsByProjectRow struct {
	ID                  uuid.UUID          `json:"id"`
	ProjectID           uuid.UUID          `json:"project_id"`
	SourceWorkspaceID   uuid.UUID          `json:"source_workspace_id"`
	TargetWorkspaceID   uuid.UUID          `json:"target_workspace_id"`
	Title               string             `json:"title"`
	Description         pgtype.Text        `json:"description"`
	AuthorID            uuid.UUID          `json:"author_id"`
	State               string             `json:"state"`
	Commits             []byte             `json:"commits"`
	FilesChanged        []byte             `json:"files_changed"`
	ReviewerID          pgtype.UUID        `json:"reviewer_id"`
	ReviewedAt          pgtype.Timestamptz `json:"reviewed_at"`
	MergedAt            pgtype.Timestamptz `json:"merged_at"`
	MergeCommitHash     pgtype.Text        `json:"merge_commit_hash"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	SourceWorkspaceName string             `json:"source_workspace_name"`
	TargetWorkspaceName string             `json:"target_workspace_name"`
	AuthorUsername      pgtype.Text        `json:"author_username"`
	AuthorAvatar        pgtype.Text        `json:"author_avatar"`
	ReviewerUsername    pgtype.Text        `json:"reviewer_username"`
}

func (q *Queries) GetChangeRequestsByProject(ctx context.Context, arg GetChangeRequestsByProjectParams) ([]GetChangeRequestsByProjectRow, error) {
	rows, err := q.db.Query(ctx, getChangeRequestsByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChangeRequestsByProjectRow{}
	for rows.Next() {
		var i GetChangeRequestsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceWorkspaceID,
			&i.TargetWorkspaceID,
			&i.Title,
			&i.Description,
			&i.AuthorID,
			&i.State,
			&i.Commits,
			&i.FilesChanged,
			&i.ReviewerID,
			&i.ReviewedAt,
			&i.MergedAt,
			&i.MergeCommitHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceWorkspaceName,
			&i.TargetWorkspaceName,
			&i.AuthorUsername,
			&i.AuthorAvatar,
			&i.ReviewerUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChangeRequestsBySourceWorkspace = `-- name: GetChangeRequestsBySourceWorkspace :many
SELECT cr.id, cr.project_id, cr.source_workspace_id, cr.target_workspace_id, cr.title, cr.description, cr.author_id, cr.state, cr.commits, cr.files_changed, cr.reviewer_id, cr.reviewed_at, cr.merged_at, cr.merge_commit_hash, cr.created_at, cr.updated_at, 
    sw.name as source_workspace_name,
    tw.name as target_workspace_name,
    u.username as author_username,
    u.avatar_url as author_avatar
FROM change_requests cr
JOIN workspaces sw ON cr.source_workspace_id = sw.id
JOIN workspaces tw ON cr.target_workspace_id = tw.id
JOIN users u ON cr.author_id = u.id
WHERE cr.source_workspace_id = $1
ORDER BY cr.created_at DESC
`

type GetChangeRequestsBySourceWorkspaceRow struct {
	ID                  uuid.UUID          `json:"id"`
	ProjectID           uuid.UUID          `json:"project_id"`
	SourceWorkspaceID   uuid.UUID          `json:"source_workspace_id"`
	TargetWorkspaceID   uuid.UUID          `json:"target_workspace_id"`
	Title               string             `json:"title"`
	Description         pgtype.Text        `json:"description"`
	AuthorID            uuid.UUID          `json:"author_id"`
	State               string             `json:"state"`
	Commits             []byte             `json:"commits"`
	FilesChanged        []byte             `json:"files_changed"`
	ReviewerID          pgtype.UUID        `json:"reviewer_id"`
	ReviewedAt          pgtype.Timestamptz `json:"reviewed_at"`
	MergedAt            pgtype.Timestamptz `json:"merged_at"`
	MergeCommitHash     pgtype.Text        `json:"merge_commit_hash"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	SourceWorkspaceName string             `json:"source_workspace_name"`
	TargetWorkspaceName string             `json:"target_workspace_name"`
	AuthorUsername      pgtype.Text        `json:"author_username"`
	AuthorAvatar        pgtype.Text        `json:"author_avatar"`
}

func (q *Queries) GetChangeRequestsBySourceWorkspace(ctx context.Context, sourceWorkspaceID uuid.UUID) ([]GetChangeRequestsBySourceWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, getChangeRequestsBySourceWorkspace, sourceWorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChangeRequestsBySourceWorkspaceRow{}
	for rows.Next() {
		var i GetChangeRequestsBySourceWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceWorkspaceID,
			&i.TargetWorkspaceID,
			&i.Title,
			&i.Description,
			&i.AuthorID,
			&i.State,
			&i.Commits,
			&i.FilesChanged,
			&i.ReviewerID,
			&i.ReviewedAt,
			&i.MergedAt,
			&i.MergeCommitHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceWorkspaceName,
			&i.TargetWorkspaceName,
			&i.AuthorUsername,
			&i.AuthorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChangeRequestsByState = `-- name: GetChangeRequestsByState :many
SELECT cr.id, cr.project_id, cr.source_workspace_id, cr.target_workspace_id, cr.title, cr.description, cr.author_id, cr.state, cr.commits, cr.files_changed, cr.reviewer_id, cr.reviewed_at, cr.merged_at, cr.merge_commit_hash, cr.created_at, cr.updated_at, 
    sw.name as source_workspace_name,
    tw.name as target_workspace_name,
    u.username as author_username,
    u.avatar_url as author_avatar
FROM change_requests cr
JOIN workspaces sw ON cr.source_workspace_id = sw.id
JOIN workspaces tw ON cr.target_workspace_id = tw.id
JOIN users u ON cr.author_id = u.id
WHERE cr.state = $1
ORDER BY cr.created_at DESC
`

type GetChangeRequestsByStateRow struct {
	ID                  uuid.UUID          `json:"id"`
	ProjectID           uuid.UUID          `json:"project_id"`
	SourceWorkspaceID   uuid.UUID          `json:"source_workspace_id"`
	TargetWorkspaceID   uuid.UUID          `json:"target_workspace_id"`
	Title               string             `json:"title"`
	Description         pgtype.Text        `json:"description"`
	AuthorID            uuid.UUID          `json:"author_id"`
	State               string             `json:"state"`
	Commits             []byte             `json:"commits"`
	FilesChanged        []byte             `json:"files_changed"`
	ReviewerID          pgtype.UUID        `json:"reviewer_id"`
	ReviewedAt          pgtype.Timestamptz `json:"reviewed_at"`
	MergedAt            pgtype.Timestamptz `json:"merged_at"`
	MergeCommitHash     pgtype.Text        `json:"merge_commit_hash"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	SourceWorkspaceName string             `json:"source_workspace_name"`
	TargetWorkspaceName string             `json:"target_workspace_name"`
	AuthorUsername      pgtype.Text        `json:"author_username"`
	AuthorAvatar        pgtype.Text        `json:"author_avatar"`
}

func (q *Queries) GetChangeRequestsByState(ctx context.Context, state string) ([]GetChangeRequestsByStateRow, error) {
	rows, err := q.db.Query(ctx, getChangeRequestsByState, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChangeRequestsByStateRow{}
	for rows.Next() {
		var i GetChangeRequestsByStateRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceWorkspaceID,
			&i.TargetWorkspaceID,
			&i.Title,
			&i.Description,
			&i.AuthorID,
			&i.State,
			&i.Commits,
			&i.FilesChanged,
			&i.ReviewerID,
			&i.ReviewedAt,
			&i.MergedAt,
			&i.MergeCommitHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceWorkspaceName,
			&i.TargetWorkspaceName,
			&i.AuthorUsername,
			&i.AuthorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChangeRequest = `-- name: UpdateChangeRequest :one
UPDATE change_requests SET
    title = COALESCE($2, title),
    description = COALESCE($3, description),
    state = COALESCE($4, state),
    commits = COALESCE($5, commits),
    files_changed = COALESCE($6, files_changed),
    reviewer_id = COALESCE($7, reviewer_id),
    reviewed_at = COALESCE($8, reviewed_at),
    merged_at = COALESCE($9, merged_at),
    merge_commit_hash = COALESCE($10, merge_commit_hash),
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, source_workspace_id, target_workspace_id, title, description, author_id, state, commits, files_changed, reviewer_id, reviewed_at, merged_at, merge_commit_hash, created_at, updated_at
`

type UpdateChangeRequestParams struct {
	ID              uuid.UUID          `json:"id"`
	Title           pgtype.Text        `json:"title"`
	Description     pgtype.Text        `json:"description"`
	State           pgtype.Text        `json:"state"`
	Commits         []byte             `json:"commits"`
	FilesChanged    []byte             `json:"files_changed"`
	ReviewerID      pgtype.UUID        `json:"reviewer_id"`
	ReviewedAt      pgtype.Timestamptz `json:"reviewed_at"`
	MergedAt        pgtype.Timestamptz `json:"merged_at"`
	MergeCommitHash pgtype.Text        `json:"merge_commit_hash"`
}

func (q *Queries) UpdateChangeRequest(ctx context.Context, arg UpdateChangeRequestParams) (ChangeRequest, error) {
	row := q.db.QueryRow(ctx, updateChangeRequest,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.State,
		arg.Commits,
		arg.FilesChanged,
		arg.ReviewerID,
		arg.ReviewedAt,
		arg.MergedAt,
		arg.MergeCommitHash,
	)
	var i ChangeRequest
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceWorkspaceID,
		&i.TargetWorkspaceID,
		&i.Title,
		&i.Description,
		&i.AuthorID,
		&i.State,
		&i.Commits,
		&i.FilesChanged,
		&i.ReviewerID,
		&i.ReviewedAt,
		&i.MergedAt,
		&i.MergeCommitHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
