// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: environment.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countEnvironmentsByStateAndRuntimeProfile = `-- name: CountEnvironmentsByStateAndRuntimeProfile :one
SELECT COUNT(*) FROM environments 
WHERE state = $1 AND deleted_at IS NULL
AND runtime_profile_id = $2
`

type CountEnvironmentsByStateAndRuntimeProfileParams struct {
	State            string      `json:"state"`
	RuntimeProfileID pgtype.UUID `json:"runtime_profile_id"`
}

func (q *Queries) CountEnvironmentsByStateAndRuntimeProfile(ctx context.Context, arg CountEnvironmentsByStateAndRuntimeProfileParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEnvironmentsByStateAndRuntimeProfile, arg.State, arg.RuntimeProfileID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (
    workspace_id, runtime_profile_id, name, state, container_id, image_id,
    public_url, port, memory_limit, cpu_limit
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, workspace_id, runtime_profile_id, name, state, container_id, image_id, public_url, port, memory_limit, cpu_limit, last_activity_at, active_sessions, suspended_at, last_error, restart_count, created_at, updated_at, deleted_at
`

type CreateEnvironmentParams struct {
	WorkspaceID      uuid.UUID   `json:"workspace_id"`
	RuntimeProfileID pgtype.UUID `json:"runtime_profile_id"`
	Name             string      `json:"name"`
	State            string      `json:"state"`
	ContainerID      pgtype.Text `json:"container_id"`
	ImageID          pgtype.UUID `json:"image_id"`
	PublicUrl        pgtype.Text `json:"public_url"`
	Port             pgtype.Int4 `json:"port"`
	MemoryLimit      pgtype.Int8 `json:"memory_limit"`
	CpuLimit         pgtype.Int8 `json:"cpu_limit"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment,
		arg.WorkspaceID,
		arg.RuntimeProfileID,
		arg.Name,
		arg.State,
		arg.ContainerID,
		arg.ImageID,
		arg.PublicUrl,
		arg.Port,
		arg.MemoryLimit,
		arg.CpuLimit,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RuntimeProfileID,
		&i.Name,
		&i.State,
		&i.ContainerID,
		&i.ImageID,
		&i.PublicUrl,
		&i.Port,
		&i.MemoryLimit,
		&i.CpuLimit,
		&i.LastActivityAt,
		&i.ActiveSessions,
		&i.SuspendedAt,
		&i.LastError,
		&i.RestartCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createEnvironmentService = `-- name: CreateEnvironmentService :one
INSERT INTO environment_services (
    environment_id, name, type, image, port, config, state, container_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, environment_id, name, type, image, port, config, state, container_id, created_at, updated_at
`

type CreateEnvironmentServiceParams struct {
	EnvironmentID uuid.UUID   `json:"environment_id"`
	Name          string      `json:"name"`
	Type          string      `json:"type"`
	Image         string      `json:"image"`
	Port          pgtype.Int4 `json:"port"`
	Config        []byte      `json:"config"`
	State         string      `json:"state"`
	ContainerID   pgtype.Text `json:"container_id"`
}

func (q *Queries) CreateEnvironmentService(ctx context.Context, arg CreateEnvironmentServiceParams) (EnvironmentService, error) {
	row := q.db.QueryRow(ctx, createEnvironmentService,
		arg.EnvironmentID,
		arg.Name,
		arg.Type,
		arg.Image,
		arg.Port,
		arg.Config,
		arg.State,
		arg.ContainerID,
	)
	var i EnvironmentService
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.Type,
		&i.Image,
		&i.Port,
		&i.Config,
		&i.State,
		&i.ContainerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEnvironmentService = `-- name: DeleteEnvironmentService :exec
DELETE FROM environment_services WHERE id = $1
`

func (q *Queries) DeleteEnvironmentService(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnvironmentService, id)
	return err
}

const getActiveEnvironmentsByWorkspace = `-- name: GetActiveEnvironmentsByWorkspace :many
SELECT id, workspace_id, runtime_profile_id, name, state, container_id, image_id, public_url, port, memory_limit, cpu_limit, last_activity_at, active_sessions, suspended_at, last_error, restart_count, created_at, updated_at, deleted_at FROM environments 
WHERE workspace_id = $1 AND deleted_at IS NULL 
AND state IN ('RUNNING', 'STARTING', 'BUILDING', 'READY')
ORDER BY created_at DESC
`

func (q *Queries) GetActiveEnvironmentsByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]Environment, error) {
	rows, err := q.db.Query(ctx, getActiveEnvironmentsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Environment{}
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RuntimeProfileID,
			&i.Name,
			&i.State,
			&i.ContainerID,
			&i.ImageID,
			&i.PublicUrl,
			&i.Port,
			&i.MemoryLimit,
			&i.CpuLimit,
			&i.LastActivityAt,
			&i.ActiveSessions,
			&i.SuspendedAt,
			&i.LastError,
			&i.RestartCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT id, workspace_id, runtime_profile_id, name, state, container_id, image_id, public_url, port, memory_limit, cpu_limit, last_activity_at, active_sessions, suspended_at, last_error, restart_count, created_at, updated_at, deleted_at FROM environments WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetEnvironment(ctx context.Context, id uuid.UUID) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironment, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RuntimeProfileID,
		&i.Name,
		&i.State,
		&i.ContainerID,
		&i.ImageID,
		&i.PublicUrl,
		&i.Port,
		&i.MemoryLimit,
		&i.CpuLimit,
		&i.LastActivityAt,
		&i.ActiveSessions,
		&i.SuspendedAt,
		&i.LastError,
		&i.RestartCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEnvironmentService = `-- name: GetEnvironmentService :one
SELECT id, environment_id, name, type, image, port, config, state, container_id, created_at, updated_at FROM environment_services WHERE id = $1
`

func (q *Queries) GetEnvironmentService(ctx context.Context, id uuid.UUID) (EnvironmentService, error) {
	row := q.db.QueryRow(ctx, getEnvironmentService, id)
	var i EnvironmentService
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.Type,
		&i.Image,
		&i.Port,
		&i.Config,
		&i.State,
		&i.ContainerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnvironmentServices = `-- name: GetEnvironmentServices :many
SELECT id, environment_id, name, type, image, port, config, state, container_id, created_at, updated_at FROM environment_services 
WHERE environment_id = $1
ORDER BY created_at
`

func (q *Queries) GetEnvironmentServices(ctx context.Context, environmentID uuid.UUID) ([]EnvironmentService, error) {
	rows, err := q.db.Query(ctx, getEnvironmentServices, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvironmentService{}
	for rows.Next() {
		var i EnvironmentService
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Name,
			&i.Type,
			&i.Image,
			&i.Port,
			&i.Config,
			&i.State,
			&i.ContainerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnvironmentsByWorkspace = `-- name: GetEnvironmentsByWorkspace :many
SELECT id, workspace_id, runtime_profile_id, name, state, container_id, image_id, public_url, port, memory_limit, cpu_limit, last_activity_at, active_sessions, suspended_at, last_error, restart_count, created_at, updated_at, deleted_at FROM environments 
WHERE workspace_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetEnvironmentsByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]Environment, error) {
	rows, err := q.db.Query(ctx, getEnvironmentsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Environment{}
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RuntimeProfileID,
			&i.Name,
			&i.State,
			&i.ContainerID,
			&i.ImageID,
			&i.PublicUrl,
			&i.Port,
			&i.MemoryLimit,
			&i.CpuLimit,
			&i.LastActivityAt,
			&i.ActiveSessions,
			&i.SuspendedAt,
			&i.LastError,
			&i.RestartCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentsByProject = `-- name: ListEnvironmentsByProject :many
SELECT e.id, e.workspace_id, e.runtime_profile_id, e.name, e.state, e.container_id, e.image_id, e.public_url, e.port, e.memory_limit, e.cpu_limit, e.last_activity_at, e.active_sessions, e.suspended_at, e.last_error, e.restart_count, e.created_at, e.updated_at, e.deleted_at FROM environments e
JOIN workspaces w ON w.id = e.workspace_id
WHERE w.project_id = $1::uuid
  AND e.deleted_at IS NULL
  AND w.deleted_at IS NULL
ORDER BY e.created_at DESC
`

// Replaces the legacy ListSandboxesByProject, which read `sandboxes` where the
// project_id column was never populated, so it always returned an empty set.
func (q *Queries) ListEnvironmentsByProject(ctx context.Context, projectID uuid.UUID) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Environment{}
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RuntimeProfileID,
			&i.Name,
			&i.State,
			&i.ContainerID,
			&i.ImageID,
			&i.PublicUrl,
			&i.Port,
			&i.MemoryLimit,
			&i.CpuLimit,
			&i.LastActivityAt,
			&i.ActiveSessions,
			&i.SuspendedAt,
			&i.LastError,
			&i.RestartCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentsByState = `-- name: ListEnvironmentsByState :many
SELECT id, workspace_id, runtime_profile_id, name, state, container_id, image_id, public_url, port, memory_limit, cpu_limit, last_activity_at, active_sessions, suspended_at, last_error, restart_count, created_at, updated_at, deleted_at FROM environments 
WHERE state = $1 AND deleted_at IS NULL
ORDER BY updated_at
`

func (q *Queries) ListEnvironmentsByState(ctx context.Context, state string) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsByState, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Environment{}
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RuntimeProfileID,
			&i.Name,
			&i.State,
			&i.ContainerID,
			&i.ImageID,
			&i.PublicUrl,
			&i.Port,
			&i.MemoryLimit,
			&i.CpuLimit,
			&i.LastActivityAt,
			&i.ActiveSessions,
			&i.SuspendedAt,
			&i.LastError,
			&i.RestartCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdleRunningEnvironments = `-- name: ListIdleRunningEnvironments :many
SELECT id, workspace_id, runtime_profile_id, name, state, container_id, image_id, public_url, port, memory_limit, cpu_limit, last_activity_at, active_sessions, suspended_at, last_error, restart_count, created_at, updated_at, deleted_at FROM environments 
WHERE state = 'RUNNING' AND deleted_at IS NULL
AND active_sessions = 0
AND (last_activity_at IS NULL OR last_activity_at < $1)
ORDER BY last_activity_at
`

func (q *Queries) ListIdleRunningEnvironments(ctx context.Context, lastActivityAt pgtype.Timestamptz) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listIdleRunningEnvironments, lastActivityAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Environment{}
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RuntimeProfileID,
			&i.Name,
			&i.State,
			&i.ContainerID,
			&i.ImageID,
			&i.PublicUrl,
			&i.Port,
			&i.MemoryLimit,
			&i.CpuLimit,
			&i.LastActivityAt,
			&i.ActiveSessions,
			&i.SuspendedAt,
			&i.LastError,
			&i.RestartCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuspendedEnvironments = `-- name: ListSuspendedEnvironments :many
SELECT id, workspace_id, runtime_profile_id, name, state, container_id, image_id, public_url, port, memory_limit, cpu_limit, last_activity_at, active_sessions, suspended_at, last_error, restart_count, created_at, updated_at, deleted_at FROM environments 
WHERE state = 'SUSPENDED' AND deleted_at IS NULL
AND suspended_at < $1
ORDER BY suspended_at
`

func (q *Queries) ListSuspendedEnvironments(ctx context.Context, suspendedAt pgtype.Timestamptz) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listSuspendedEnvironments, suspendedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Environment{}
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RuntimeProfileID,
			&i.Name,
			&i.State,
			&i.ContainerID,
			&i.ImageID,
			&i.PublicUrl,
			&i.Port,
			&i.MemoryLimit,
			&i.CpuLimit,
			&i.LastActivityAt,
			&i.ActiveSessions,
			&i.SuspendedAt,
			&i.LastError,
			&i.RestartCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteEnvironment = `-- name: SoftDeleteEnvironment :exec
UPDATE environments SET deleted_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteEnvironment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteEnvironment, id)
	return err
}

const updateEnvironment = `-- name: UpdateEnvironment :one
UPDATE environments SET
    name = COALESCE($2, name),
    runtime_profile_id = COALESCE($3, runtime_profile_id),
    container_id = COALESCE($4, container_id),
    image_id = COALESCE($5, image_id),
    public_url = COALESCE($6, public_url),
    port = COALESCE($7, port),
    memory_limit = COALESCE($8, memory_limit),
    cpu_limit = COALESCE($9, cpu_limit),
    last_activity_at = COALESCE($10, last_activity_at),
    active_sessions = COALESCE($11, active_sessions),
    suspended_at = COALESCE($12, suspended_at),
    last_error = COALESCE($13, last_error),
    restart_count = COALESCE($14, restart_count),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workspace_id, runtime_profile_id, name, state, container_id, image_id, public_url, port, memory_limit, cpu_limit, last_activity_at, active_sessions, suspended_at, last_error, restart_count, created_at, updated_at, deleted_at
`

type UpdateEnvironmentParams struct {
	ID               uuid.UUID          `json:"id"`
	Name             pgtype.Text        `json:"name"`
	RuntimeProfileID pgtype.UUID        `json:"runtime_profile_id"`
	ContainerID      pgtype.Text        `json:"container_id"`
	ImageID          pgtype.UUID        `json:"image_id"`
	PublicUrl        pgtype.Text        `json:"public_url"`
	Port             pgtype.Int4        `json:"port"`
	MemoryLimit      pgtype.Int8        `json:"memory_limit"`
	CpuLimit         pgtype.Int8        `json:"cpu_limit"`
	LastActivityAt   pgtype.Timestamptz `json:"last_activity_at"`
	ActiveSessions   pgtype.Int4        `json:"active_sessions"`
	SuspendedAt      pgtype.Timestamptz `json:"suspended_at"`
	LastError        pgtype.Text        `json:"last_error"`
	RestartCount     pgtype.Int4        `json:"restart_count"`
}

func (q *Queries) UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, updateEnvironment,
		arg.ID,
		arg.Name,
		arg.RuntimeProfileID,
		arg.ContainerID,
		arg.ImageID,
		arg.PublicUrl,
		arg.Port,
		arg.MemoryLimit,
		arg.CpuLimit,
		arg.LastActivityAt,
		arg.ActiveSessions,
		arg.SuspendedAt,
		arg.LastError,
		arg.RestartCount,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RuntimeProfileID,
		&i.Name,
		&i.State,
		&i.ContainerID,
		&i.ImageID,
		&i.PublicUrl,
		&i.Port,
		&i.MemoryLimit,
		&i.CpuLimit,
		&i.LastActivityAt,
		&i.ActiveSessions,
		&i.SuspendedAt,
		&i.LastError,
		&i.RestartCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateEnvironmentActivity = `-- name: UpdateEnvironmentActivity :one
UPDATE environments SET
    last_activity_at = NOW(),
    active_sessions = $2,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workspace_id, runtime_profile_id, name, state, container_id, image_id, public_url, port, memory_limit, cpu_limit, last_activity_at, active_sessions, suspended_at, last_error, restart_count, created_at, updated_at, deleted_at
`

type UpdateEnvironmentActivityParams struct {
	ID             uuid.UUID   `json:"id"`
	ActiveSessions pgtype.Int4 `json:"active_sessions"`
}

func (q *Queries) UpdateEnvironmentActivity(ctx context.Context, arg UpdateEnvironmentActivityParams) (Environment, error) {
	row := q.db.QueryRow(ctx, updateEnvironmentActivity, arg.ID, arg.ActiveSessions)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RuntimeProfileID,
		&i.Name,
		&i.State,
		&i.ContainerID,
		&i.ImageID,
		&i.PublicUrl,
		&i.Port,
		&i.MemoryLimit,
		&i.CpuLimit,
		&i.LastActivityAt,
		&i.ActiveSessions,
		&i.SuspendedAt,
		&i.LastError,
		&i.RestartCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateEnvironmentContainerID = `-- name: UpdateEnvironmentContainerID :one
UPDATE environments SET
    container_id = $2,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workspace_id, runtime_profile_id, name, state, container_id, image_id, public_url, port, memory_limit, cpu_limit, last_activity_at, active_sessions, suspended_at, last_error, restart_count, created_at, updated_at, deleted_at
`

type UpdateEnvironmentContainerIDParams struct {
	ID          uuid.UUID   `json:"id"`
	ContainerID pgtype.Text `json:"container_id"`
}

func (q *Queries) UpdateEnvironmentContainerID(ctx context.Context, arg UpdateEnvironmentContainerIDParams) (Environment, error) {
	row := q.db.QueryRow(ctx, updateEnvironmentContainerID, arg.ID, arg.ContainerID)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RuntimeProfileID,
		&i.Name,
		&i.State,
		&i.ContainerID,
		&i.ImageID,
		&i.PublicUrl,
		&i.Port,
		&i.MemoryLimit,
		&i.CpuLimit,
		&i.LastActivityAt,
		&i.ActiveSessions,
		&i.SuspendedAt,
		&i.LastError,
		&i.RestartCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateEnvironmentImageID = `-- name: UpdateEnvironmentImageID :one
UPDATE environments SET
    image_id = $2,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workspace_id, runtime_profile_id, name, state, container_id, image_id, public_url, port, memory_limit, cpu_limit, last_activity_at, active_sessions, suspended_at, last_error, restart_count, created_at, updated_at, deleted_at
`

type UpdateEnvironmentImageIDParams struct {
	ID      uuid.UUID   `json:"id"`
	ImageID pgtype.UUID `json:"image_id"`
}

func (q *Queries) UpdateEnvironmentImageID(ctx context.Context, arg UpdateEnvironmentImageIDParams) (Environment, error) {
	row := q.db.QueryRow(ctx, updateEnvironmentImageID, arg.ID, arg.ImageID)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RuntimeProfileID,
		&i.Name,
		&i.State,
		&i.ContainerID,
		&i.ImageID,
		&i.PublicUrl,
		&i.Port,
		&i.MemoryLimit,
		&i.CpuLimit,
		&i.LastActivityAt,
		&i.ActiveSessions,
		&i.SuspendedAt,
		&i.LastError,
		&i.RestartCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateEnvironmentService = `-- name: UpdateEnvironmentService :one
UPDATE environment_services SET
    state = COALESCE($2, state),
    container_id = COALESCE($3, container_id),
    config = COALESCE($4, config),
    updated_at = NOW()
WHERE id = $1
RETURNING id, environment_id, name, type, image, port, config, state, container_id, created_at, updated_at
`

type UpdateEnvironmentServiceParams struct {
	ID          uuid.UUID   `json:"id"`
	State       pgtype.Text `json:"state"`
	ContainerID pgtype.Text `json:"container_id"`
	Config      []byte      `json:"config"`
}

func (q *Queries) UpdateEnvironmentService(ctx context.Context, arg UpdateEnvironmentServiceParams) (EnvironmentService, error) {
	row := q.db.QueryRow(ctx, updateEnvironmentService,
		arg.ID,
		arg.State,
		arg.ContainerID,
		arg.Config,
	)
	var i EnvironmentService
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.Type,
		&i.Image,
		&i.Port,
		&i.Config,
		&i.State,
		&i.ContainerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEnvironmentState = `-- name: UpdateEnvironmentState :one
UPDATE environments SET
    state = $2,
    last_error = COALESCE($3, last_error),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workspace_id, runtime_profile_id, name, state, container_id, image_id, public_url, port, memory_limit, cpu_limit, last_activity_at, active_sessions, suspended_at, last_error, restart_count, created_at, updated_at, deleted_at
`

type UpdateEnvironmentStateParams struct {
	ID        uuid.UUID   `json:"id"`
	State     string      `json:"state"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) UpdateEnvironmentState(ctx context.Context, arg UpdateEnvironmentStateParams) (Environment, error) {
	row := q.db.QueryRow(ctx, updateEnvironmentState, arg.ID, arg.State, arg.LastError)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RuntimeProfileID,
		&i.Name,
		&i.State,
		&i.ContainerID,
		&i.ImageID,
		&i.PublicUrl,
		&i.Port,
		&i.MemoryLimit,
		&i.CpuLimit,
		&i.LastActivityAt,
		&i.ActiveSessions,
		&i.SuspendedAt,
		&i.LastError,
		&i.RestartCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
