// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: environment_event.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEnvironmentEvent = `-- name: CreateEnvironmentEvent :one
INSERT INTO environment_events (
    environment_id, workspace_id, project_id, user_id, type, payload
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, environment_id, workspace_id, project_id, user_id, type, payload, created_at
`

type CreateEnvironmentEventParams struct {
	EnvironmentID uuid.UUID   `json:"environment_id"`
	WorkspaceID   uuid.UUID   `json:"workspace_id"`
	ProjectID     uuid.UUID   `json:"project_id"`
	UserID        pgtype.UUID `json:"user_id"`
	Type          string      `json:"type"`
	Payload       []byte      `json:"payload"`
}

func (q *Queries) CreateEnvironmentEvent(ctx context.Context, arg CreateEnvironmentEventParams) (EnvironmentEvent, error) {
	row := q.db.QueryRow(ctx, createEnvironmentEvent,
		arg.EnvironmentID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.UserID,
		arg.Type,
		arg.Payload,
	)
	var i EnvironmentEvent
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.UserID,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getEnvironmentEvents = `-- name: GetEnvironmentEvents :many
SELECT ee.id, ee.environment_id, ee.workspace_id, ee.project_id, ee.user_id, ee.type, ee.payload, ee.created_at, u.username, u.avatar_url
FROM environment_events ee
LEFT JOIN users u ON ee.user_id = u.id
WHERE ee.environment_id = $1
ORDER BY ee.created_at DESC
LIMIT $2 OFFSET $3
`

type GetEnvironmentEventsParams struct {
	EnvironmentID uuid.UUID `json:"environment_id"`
	Limit         int32     `json:"limit"`
	Offset        int32     `json:"offset"`
}

type GetEnvironmentEventsRow struct {
	ID            uuid.UUID          `json:"id"`
	EnvironmentID uuid.UUID          `json:"environment_id"`
	WorkspaceID   uuid.UUID          `json:"workspace_id"`
	ProjectID     uuid.UUID          `json:"project_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Type          string             `json:"type"`
	Payload       []byte             `json:"payload"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Username      pgtype.Text        `json:"username"`
	AvatarUrl     pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) GetEnvironmentEvents(ctx context.Context, arg GetEnvironmentEventsParams) ([]GetEnvironmentEventsRow, error) {
	rows, err := q.db.Query(ctx, getEnvironmentEvents, arg.EnvironmentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEnvironmentEventsRow{}
	for rows.Next() {
		var i GetEnvironmentEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.UserID,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
			&i.Username,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectEvents = `-- name: GetProjectEvents :many
SELECT ee.id, ee.environment_id, ee.workspace_id, ee.project_id, ee.user_id, ee.type, ee.payload, ee.created_at, u.username, u.avatar_url
FROM environment_events ee
LEFT JOIN users u ON ee.user_id = u.id
WHERE ee.project_id = $1
ORDER BY ee.created_at DESC
LIMIT $2 OFFSET $3
`

type GetProjectEventsParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type GetProjectEventsRow struct {
	ID            uuid.UUID          `json:"id"`
	EnvironmentID uuid.UUID          `json:"environment_id"`
	WorkspaceID   uuid.UUID          `json:"workspace_id"`
	ProjectID     uuid.UUID          `json:"project_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Type          string             `json:"type"`
	Payload       []byte             `json:"payload"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Username      pgtype.Text        `json:"username"`
	AvatarUrl     pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) GetProjectEvents(ctx context.Context, arg GetProjectEventsParams) ([]GetProjectEventsRow, error) {
	rows, err := q.db.Query(ctx, getProjectEvents, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProjectEventsRow{}
	for rows.Next() {
		var i GetProjectEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.UserID,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
			&i.Username,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentProjectEvents = `-- name: GetRecentProjectEvents :many
SELECT ee.id, ee.environment_id, ee.workspace_id, ee.project_id, ee.user_id, ee.type, ee.payload, ee.created_at, u.username, u.avatar_url
FROM environment_events ee
LEFT JOIN users u ON ee.user_id = u.id
WHERE ee.project_id = $1 AND ee.created_at > $2
ORDER BY ee.created_at DESC
LIMIT $3
`

type GetRecentProjectEventsParams struct {
	ProjectID uuid.UUID          `json:"project_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Limit     int32              `json:"limit"`
}

type GetRecentProjectEventsRow struct {
	ID            uuid.UUID          `json:"id"`
	EnvironmentID uuid.UUID          `json:"environment_id"`
	WorkspaceID   uuid.UUID          `json:"workspace_id"`
	ProjectID     uuid.UUID          `json:"project_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Type          string             `json:"type"`
	Payload       []byte             `json:"payload"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Username      pgtype.Text        `json:"username"`
	AvatarUrl     pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) GetRecentProjectEvents(ctx context.Context, arg GetRecentProjectEventsParams) ([]GetRecentProjectEventsRow, error) {
	rows, err := q.db.Query(ctx, getRecentProjectEvents, arg.ProjectID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentProjectEventsRow{}
	for rows.Next() {
		var i GetRecentProjectEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.UserID,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
			&i.Username,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceEvents = `-- name: GetWorkspaceEvents :many
SELECT ee.id, ee.environment_id, ee.workspace_id, ee.project_id, ee.user_id, ee.type, ee.payload, ee.created_at, u.username, u.avatar_url
FROM environment_events ee
LEFT JOIN users u ON ee.user_id = u.id
WHERE ee.workspace_id = $1
ORDER BY ee.created_at DESC
LIMIT $2 OFFSET $3
`

type GetWorkspaceEventsParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

type GetWorkspaceEventsRow struct {
	ID            uuid.UUID          `json:"id"`
	EnvironmentID uuid.UUID          `json:"environment_id"`
	WorkspaceID   uuid.UUID          `json:"workspace_id"`
	ProjectID     uuid.UUID          `json:"project_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Type          string             `json:"type"`
	Payload       []byte             `json:"payload"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Username      pgtype.Text        `json:"username"`
	AvatarUrl     pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) GetWorkspaceEvents(ctx context.Context, arg GetWorkspaceEventsParams) ([]GetWorkspaceEventsRow, error) {
	rows, err := q.db.Query(ctx, getWorkspaceEvents, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWorkspaceEventsRow{}
	for rows.Next() {
		var i GetWorkspaceEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.UserID,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
			&i.Username,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
