// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: project.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addProjectCollaborator = `-- name: AddProjectCollaborator :one
INSERT INTO project_collaborators (project_id, user_id, role, invited_by_user_id, invited_at)
VALUES ($1, $2, $3, $4, NOW())
RETURNING id, project_id, user_id, role, invited_by_user_id, invited_at, accepted_at
`

type AddProjectCollaboratorParams struct {
	ProjectID       uuid.UUID   `json:"project_id"`
	UserID          uuid.UUID   `json:"user_id"`
	Role            string      `json:"role"`
	InvitedByUserID pgtype.UUID `json:"invited_by_user_id"`
}

func (q *Queries) AddProjectCollaborator(ctx context.Context, arg AddProjectCollaboratorParams) (ProjectCollaborator, error) {
	row := q.db.QueryRow(ctx, addProjectCollaborator,
		arg.ProjectID,
		arg.UserID,
		arg.Role,
		arg.InvitedByUserID,
	)
	var i ProjectCollaborator
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.InvitedByUserID,
		&i.InvitedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, description, owner_organization_id, created_by_user_id, is_public)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, owner_organization_id, created_by_user_id, is_public, created_at, updated_at
`

type CreateProjectParams struct {
	Name                string      `json:"name"`
	Description         pgtype.Text `json:"description"`
	OwnerOrganizationID uuid.UUID   `json:"owner_organization_id"`
	CreatedByUserID     uuid.UUID   `json:"created_by_user_id"`
	IsPublic            pgtype.Bool `json:"is_public"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Name,
		arg.Description,
		arg.OwnerOrganizationID,
		arg.CreatedByUserID,
		arg.IsPublic,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerOrganizationID,
		&i.CreatedByUserID,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, description, owner_organization_id, created_by_user_id, is_public, created_at, updated_at FROM projects WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerOrganizationID,
		&i.CreatedByUserID,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectCollaborator = `-- name: GetProjectCollaborator :one
SELECT id, project_id, user_id, role, invited_by_user_id, invited_at, accepted_at FROM project_collaborators 
WHERE project_id = $1 AND user_id = $2 LIMIT 1
`

type GetProjectCollaboratorParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetProjectCollaborator(ctx context.Context, arg GetProjectCollaboratorParams) (ProjectCollaborator, error) {
	row := q.db.QueryRow(ctx, getProjectCollaborator, arg.ProjectID, arg.UserID)
	var i ProjectCollaborator
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.InvitedByUserID,
		&i.InvitedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const listProjectCollaborators = `-- name: ListProjectCollaborators :many
SELECT pc.id, pc.project_id, pc.user_id, pc.role, pc.invited_at, pc.accepted_at, u.username, u.email, u.avatar_url 
FROM project_collaborators pc
JOIN users u ON u.id = pc.user_id
WHERE pc.project_id = $1
ORDER BY pc.invited_at ASC
`

type ListProjectCollaboratorsRow struct {
	ID         uuid.UUID          `json:"id"`
	ProjectID  uuid.UUID          `json:"project_id"`
	UserID     uuid.UUID          `json:"user_id"`
	Role       string             `json:"role"`
	InvitedAt  pgtype.Timestamptz `json:"invited_at"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	Username   pgtype.Text        `json:"username"`
	Email      string             `json:"email"`
	AvatarUrl  pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) ListProjectCollaborators(ctx context.Context, projectID uuid.UUID) ([]ListProjectCollaboratorsRow, error) {
	rows, err := q.db.Query(ctx, listProjectCollaborators, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectCollaboratorsRow{}
	for rows.Next() {
		var i ListProjectCollaboratorsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.InvitedAt,
			&i.AcceptedAt,
			&i.Username,
			&i.Email,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsForOrg = `-- name: ListProjectsForOrg :many
SELECT id, name, description, owner_organization_id, created_by_user_id, is_public, created_at, updated_at FROM projects WHERE owner_organization_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListProjectsForOrg(ctx context.Context, ownerOrganizationID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsForOrg, ownerOrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerOrganizationID,
			&i.CreatedByUserID,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsForUser = `-- name: ListProjectsForUser :many
SELECT p.id, p.name, p.description, p.owner_organization_id, p.created_by_user_id, p.is_public, p.created_at, p.updated_at, pc.role
FROM projects p
JOIN project_collaborators pc ON p.id = pc.project_id
WHERE pc.user_id = $1
ORDER BY p.created_at DESC
`

type ListProjectsForUserRow struct {
	ID                  uuid.UUID          `json:"id"`
	Name                string             `json:"name"`
	Description         pgtype.Text        `json:"description"`
	OwnerOrganizationID uuid.UUID          `json:"owner_organization_id"`
	CreatedByUserID     uuid.UUID          `json:"created_by_user_id"`
	IsPublic            pgtype.Bool        `json:"is_public"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	Role                string             `json:"role"`
}

func (q *Queries) ListProjectsForUser(ctx context.Context, userID uuid.UUID) ([]ListProjectsForUserRow, error) {
	rows, err := q.db.Query(ctx, listProjectsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsForUserRow{}
	for rows.Next() {
		var i ListProjectsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerOrganizationID,
			&i.CreatedByUserID,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectCollaborator = `-- name: RemoveProjectCollaborator :exec
DELETE FROM project_collaborators
WHERE project_id = $1 AND user_id = $2
`

type RemoveProjectCollaboratorParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveProjectCollaborator(ctx context.Context, arg RemoveProjectCollaboratorParams) error {
	_, err := q.db.Exec(ctx, removeProjectCollaborator, arg.ProjectID, arg.UserID)
	return err
}

const updateProjectRole = `-- name: UpdateProjectRole :exec
UPDATE project_collaborators
SET role = $3
WHERE project_id = $1 AND user_id = $2
`

type UpdateProjectRoleParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
}

func (q *Queries) UpdateProjectRole(ctx context.Context, arg UpdateProjectRoleParams) error {
	_, err := q.db.Exec(ctx, updateProjectRole, arg.ProjectID, arg.UserID, arg.Role)
	return err
}
