// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountSandboxesByOwner(ctx context.Context, ownerID uuid.UUID) (int64, error)
	CreateSandbox(ctx context.Context, arg CreateSandboxParams) (Sandbox, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteSandbox(ctx context.Context, id uuid.UUID) error
	GetSandboxByID(ctx context.Context, id uuid.UUID) (Sandbox, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByGithubID(ctx context.Context, githubID pgtype.Text) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListSandboxesByOwner(ctx context.Context, ownerID uuid.UUID) ([]Sandbox, error)
	ListSandboxesByProject(ctx context.Context, projectID pgtype.UUID) ([]Sandbox, error)
	UpdateSandboxContainer(ctx context.Context, arg UpdateSandboxContainerParams) error
	UpdateSandboxState(ctx context.Context, arg UpdateSandboxStateParams) error
	UpdateUserToken(ctx context.Context, arg UpdateUserTokenParams) error
}

var _ Querier = (*Queries)(nil)
