// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: runtime_profile.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmRuntimeProfile = `-- name: ConfirmRuntimeProfile :one
UPDATE runtime_profiles SET
    status = 'CONFIRMED',
    confirmed_by = $2,
    confirmed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, workspace_id, detection_evidence, language, version, framework, package_manager, architecture, entrypoint, build_command, start_command, port, dockerfile_source, dockerfile_content, requires_database, requires_redis, confidence, status, confirmed_by, confirmed_at, created_at, updated_at
`

type ConfirmRuntimeProfileParams struct {
	ID          uuid.UUID   `json:"id"`
	ConfirmedBy pgtype.UUID `json:"confirmed_by"`
}

func (q *Queries) ConfirmRuntimeProfile(ctx context.Context, arg ConfirmRuntimeProfileParams) (RuntimeProfile, error) {
	row := q.db.QueryRow(ctx, confirmRuntimeProfile, arg.ID, arg.ConfirmedBy)
	var i RuntimeProfile
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.DetectionEvidence,
		&i.Language,
		&i.Version,
		&i.Framework,
		&i.PackageManager,
		&i.Architecture,
		&i.Entrypoint,
		&i.BuildCommand,
		&i.StartCommand,
		&i.Port,
		&i.DockerfileSource,
		&i.DockerfileContent,
		&i.RequiresDatabase,
		&i.RequiresRedis,
		&i.Confidence,
		&i.Status,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRuntimeProfile = `-- name: CreateRuntimeProfile :one
INSERT INTO runtime_profiles (
    project_id, workspace_id, detection_evidence, language, version, framework,
    package_manager, architecture, entrypoint, build_command, start_command,
    port, dockerfile_source, dockerfile_content, requires_database, requires_redis,
    confidence, status, confirmed_by, confirmed_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20
) RETURNING id, project_id, workspace_id, detection_evidence, language, version, framework, package_manager, architecture, entrypoint, build_command, start_command, port, dockerfile_source, dockerfile_content, requires_database, requires_redis, confidence, status, confirmed_by, confirmed_at, created_at, updated_at
`

type CreateRuntimeProfileParams struct {
	ProjectID         pgtype.UUID        `json:"project_id"`
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	DetectionEvidence []byte             `json:"detection_evidence"`
	Language          string             `json:"language"`
	Version           pgtype.Text        `json:"version"`
	Framework         pgtype.Text        `json:"framework"`
	PackageManager    pgtype.Text        `json:"package_manager"`
	Architecture      pgtype.Text        `json:"architecture"`
	Entrypoint        pgtype.Text        `json:"entrypoint"`
	BuildCommand      pgtype.Text        `json:"build_command"`
	StartCommand      pgtype.Text        `json:"start_command"`
	Port              pgtype.Int4        `json:"port"`
	DockerfileSource  pgtype.Text        `json:"dockerfile_source"`
	DockerfileContent pgtype.Text        `json:"dockerfile_content"`
	RequiresDatabase  pgtype.Bool        `json:"requires_database"`
	RequiresRedis     pgtype.Bool        `json:"requires_redis"`
	Confidence        float32            `json:"confidence"`
	Status            string             `json:"status"`
	ConfirmedBy       pgtype.UUID        `json:"confirmed_by"`
	ConfirmedAt       pgtype.Timestamptz `json:"confirmed_at"`
}

func (q *Queries) CreateRuntimeProfile(ctx context.Context, arg CreateRuntimeProfileParams) (RuntimeProfile, error) {
	row := q.db.QueryRow(ctx, createRuntimeProfile,
		arg.ProjectID,
		arg.WorkspaceID,
		arg.DetectionEvidence,
		arg.Language,
		arg.Version,
		arg.Framework,
		arg.PackageManager,
		arg.Architecture,
		arg.Entrypoint,
		arg.BuildCommand,
		arg.StartCommand,
		arg.Port,
		arg.DockerfileSource,
		arg.DockerfileContent,
		arg.RequiresDatabase,
		arg.RequiresRedis,
		arg.Confidence,
		arg.Status,
		arg.ConfirmedBy,
		arg.ConfirmedAt,
	)
	var i RuntimeProfile
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.DetectionEvidence,
		&i.Language,
		&i.Version,
		&i.Framework,
		&i.PackageManager,
		&i.Architecture,
		&i.Entrypoint,
		&i.BuildCommand,
		&i.StartCommand,
		&i.Port,
		&i.DockerfileSource,
		&i.DockerfileContent,
		&i.RequiresDatabase,
		&i.RequiresRedis,
		&i.Confidence,
		&i.Status,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRuntimeProfile = `-- name: DeleteRuntimeProfile :exec
DELETE FROM runtime_profiles WHERE id = $1
`

func (q *Queries) DeleteRuntimeProfile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRuntimeProfile, id)
	return err
}

const getLatestRuntimeProfileByWorkspace = `-- name: GetLatestRuntimeProfileByWorkspace :one
SELECT id, project_id, workspace_id, detection_evidence, language, version, framework, package_manager, architecture, entrypoint, build_command, start_command, port, dockerfile_source, dockerfile_content, requires_database, requires_redis, confidence, status, confirmed_by, confirmed_at, created_at, updated_at FROM runtime_profiles 
WHERE workspace_id = $1 
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestRuntimeProfileByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (RuntimeProfile, error) {
	row := q.db.QueryRow(ctx, getLatestRuntimeProfileByWorkspace, workspaceID)
	var i RuntimeProfile
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.DetectionEvidence,
		&i.Language,
		&i.Version,
		&i.Framework,
		&i.PackageManager,
		&i.Architecture,
		&i.Entrypoint,
		&i.BuildCommand,
		&i.StartCommand,
		&i.Port,
		&i.DockerfileSource,
		&i.DockerfileContent,
		&i.RequiresDatabase,
		&i.RequiresRedis,
		&i.Confidence,
		&i.Status,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRuntimeProfile = `-- name: GetRuntimeProfile :one
SELECT id, project_id, workspace_id, detection_evidence, language, version, framework, package_manager, architecture, entrypoint, build_command, start_command, port, dockerfile_source, dockerfile_content, requires_database, requires_redis, confidence, status, confirmed_by, confirmed_at, created_at, updated_at FROM runtime_profiles WHERE id = $1
`

func (q *Queries) GetRuntimeProfile(ctx context.Context, id uuid.UUID) (RuntimeProfile, error) {
	row := q.db.QueryRow(ctx, getRuntimeProfile, id)
	var i RuntimeProfile
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.DetectionEvidence,
		&i.Language,
		&i.Version,
		&i.Framework,
		&i.PackageManager,
		&i.Architecture,
		&i.Entrypoint,
		&i.BuildCommand,
		&i.StartCommand,
		&i.Port,
		&i.DockerfileSource,
		&i.DockerfileContent,
		&i.RequiresDatabase,
		&i.RequiresRedis,
		&i.Confidence,
		&i.Status,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRuntimeProfilesByProject = `-- name: GetRuntimeProfilesByProject :many
SELECT id, project_id, workspace_id, detection_evidence, language, version, framework, package_manager, architecture, entrypoint, build_command, start_command, port, dockerfile_source, dockerfile_content, requires_database, requires_redis, confidence, status, confirmed_by, confirmed_at, created_at, updated_at FROM runtime_profiles WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetRuntimeProfilesByProject(ctx context.Context, projectID pgtype.UUID) ([]RuntimeProfile, error) {
	rows, err := q.db.Query(ctx, getRuntimeProfilesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RuntimeProfile{}
	for rows.Next() {
		var i RuntimeProfile
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.WorkspaceID,
			&i.DetectionEvidence,
			&i.Language,
			&i.Version,
			&i.Framework,
			&i.PackageManager,
			&i.Architecture,
			&i.Entrypoint,
			&i.BuildCommand,
			&i.StartCommand,
			&i.Port,
			&i.DockerfileSource,
			&i.DockerfileContent,
			&i.RequiresDatabase,
			&i.RequiresRedis,
			&i.Confidence,
			&i.Status,
			&i.ConfirmedBy,
			&i.ConfirmedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRuntimeProfilesByWorkspace = `-- name: GetRuntimeProfilesByWorkspace :many
SELECT id, project_id, workspace_id, detection_evidence, language, version, framework, package_manager, architecture, entrypoint, build_command, start_command, port, dockerfile_source, dockerfile_content, requires_database, requires_redis, confidence, status, confirmed_by, confirmed_at, created_at, updated_at FROM runtime_profiles WHERE workspace_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetRuntimeProfilesByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]RuntimeProfile, error) {
	rows, err := q.db.Query(ctx, getRuntimeProfilesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RuntimeProfile{}
	for rows.Next() {
		var i RuntimeProfile
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.WorkspaceID,
			&i.DetectionEvidence,
			&i.Language,
			&i.Version,
			&i.Framework,
			&i.PackageManager,
			&i.Architecture,
			&i.Entrypoint,
			&i.BuildCommand,
			&i.StartCommand,
			&i.Port,
			&i.DockerfileSource,
			&i.DockerfileContent,
			&i.RequiresDatabase,
			&i.RequiresRedis,
			&i.Confidence,
			&i.Status,
			&i.ConfirmedBy,
			&i.ConfirmedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRuntimeProfile = `-- name: UpdateRuntimeProfile :one
UPDATE runtime_profiles SET
    detection_evidence = COALESCE($2, detection_evidence),
    language = COALESCE($3, language),
    version = COALESCE($4, version),
    framework = COALESCE($5, framework),
    package_manager = COALESCE($6, package_manager),
    architecture = COALESCE($7, architecture),
    entrypoint = COALESCE($8, entrypoint),
    build_command = COALESCE($9, build_command),
    start_command = COALESCE($10, start_command),
    port = COALESCE($11, port),
    dockerfile_source = COALESCE($12, dockerfile_source),
    dockerfile_content = COALESCE($13, dockerfile_content),
    requires_database = COALESCE($14, requires_database),
    requires_redis = COALESCE($15, requires_redis),
    confidence = COALESCE($16, confidence),
    status = COALESCE($17, status),
    confirmed_by = COALESCE($18, confirmed_by),
    confirmed_at = COALESCE($19, confirmed_at),
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, workspace_id, detection_evidence, language, version, framework, package_manager, architecture, entrypoint, build_command, start_command, port, dockerfile_source, dockerfile_content, requires_database, requires_redis, confidence, status, confirmed_by, confirmed_at, created_at, updated_at
`

type UpdateRuntimeProfileParams struct {
	ID                uuid.UUID          `json:"id"`
	DetectionEvidence []byte             `json:"detection_evidence"`
	Language          pgtype.Text        `json:"language"`
	Version           pgtype.Text        `json:"version"`
	Framework         pgtype.Text        `json:"framework"`
	PackageManager    pgtype.Text        `json:"package_manager"`
	Architecture      pgtype.Text        `json:"architecture"`
	Entrypoint        pgtype.Text        `json:"entrypoint"`
	BuildCommand      pgtype.Text        `json:"build_command"`
	StartCommand      pgtype.Text        `json:"start_command"`
	Port              pgtype.Int4        `json:"port"`
	DockerfileSource  pgtype.Text        `json:"dockerfile_source"`
	DockerfileContent pgtype.Text        `json:"dockerfile_content"`
	RequiresDatabase  pgtype.Bool        `json:"requires_database"`
	RequiresRedis     pgtype.Bool        `json:"requires_redis"`
	Confidence        pgtype.Float4      `json:"confidence"`
	Status            pgtype.Text        `json:"status"`
	ConfirmedBy       pgtype.UUID        `json:"confirmed_by"`
	ConfirmedAt       pgtype.Timestamptz `json:"confirmed_at"`
}

func (q *Queries) UpdateRuntimeProfile(ctx context.Context, arg UpdateRuntimeProfileParams) (RuntimeProfile, error) {
	row := q.db.QueryRow(ctx, updateRuntimeProfile,
		arg.ID,
		arg.DetectionEvidence,
		arg.Language,
		arg.Version,
		arg.Framework,
		arg.PackageManager,
		arg.Architecture,
		arg.Entrypoint,
		arg.BuildCommand,
		arg.StartCommand,
		arg.Port,
		arg.DockerfileSource,
		arg.DockerfileContent,
		arg.RequiresDatabase,
		arg.RequiresRedis,
		arg.Confidence,
		arg.Status,
		arg.ConfirmedBy,
		arg.ConfirmedAt,
	)
	var i RuntimeProfile
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.DetectionEvidence,
		&i.Language,
		&i.Version,
		&i.Framework,
		&i.PackageManager,
		&i.Architecture,
		&i.Entrypoint,
		&i.BuildCommand,
		&i.StartCommand,
		&i.Port,
		&i.DockerfileSource,
		&i.DockerfileContent,
		&i.RequiresDatabase,
		&i.RequiresRedis,
		&i.Confidence,
		&i.Status,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
