// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sandbox.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSandbox = `-- name: CreateSandbox :one
INSERT INTO sandboxes (
    project_id, owner_id, name, git_url, git_branch, state,
    runtime_language, runtime_base_image, runtime_port, needs_db
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, project_id, owner_id, name, git_url, git_branch, state, runtime_language, runtime_base_image, runtime_port, needs_db, container_id, public_url, created_at, updated_at, expires_at
`

type CreateSandboxParams struct {
	ProjectID        pgtype.UUID `json:"project_id"`
	OwnerID          uuid.UUID   `json:"owner_id"`
	Name             string      `json:"name"`
	GitUrl           string      `json:"git_url"`
	GitBranch        string      `json:"git_branch"`
	State            string      `json:"state"`
	RuntimeLanguage  pgtype.Text `json:"runtime_language"`
	RuntimeBaseImage pgtype.Text `json:"runtime_base_image"`
	RuntimePort      pgtype.Int4 `json:"runtime_port"`
	NeedsDb          pgtype.Bool `json:"needs_db"`
}

func (q *Queries) CreateSandbox(ctx context.Context, arg CreateSandboxParams) (Sandbox, error) {
	row := q.db.QueryRow(ctx, createSandbox,
		arg.ProjectID,
		arg.OwnerID,
		arg.Name,
		arg.GitUrl,
		arg.GitBranch,
		arg.State,
		arg.RuntimeLanguage,
		arg.RuntimeBaseImage,
		arg.RuntimePort,
		arg.NeedsDb,
	)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OwnerID,
		&i.Name,
		&i.GitUrl,
		&i.GitBranch,
		&i.State,
		&i.RuntimeLanguage,
		&i.RuntimeBaseImage,
		&i.RuntimePort,
		&i.NeedsDb,
		&i.ContainerID,
		&i.PublicUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, username, github_id, github_username, avatar_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, username, github_id, github_username, github_token_encrypted, avatar_url, max_sandboxes, max_builds_per_hour, created_at, updated_at
`

type CreateUserParams struct {
	Email          string      `json:"email"`
	Username       pgtype.Text `json:"username"`
	GithubID       pgtype.Text `json:"github_id"`
	GithubUsername pgtype.Text `json:"github_username"`
	AvatarUrl      pgtype.Text `json:"avatar_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.GithubID,
		arg.GithubUsername,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.GithubID,
		&i.GithubUsername,
		&i.GithubTokenEncrypted,
		&i.AvatarUrl,
		&i.MaxSandboxes,
		&i.MaxBuildsPerHour,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSandbox = `-- name: DeleteSandbox :exec
DELETE FROM sandboxes WHERE id = $1
`

func (q *Queries) DeleteSandbox(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSandbox, id)
	return err
}

const getSandboxByID = `-- name: GetSandboxByID :one
SELECT id, project_id, owner_id, name, git_url, git_branch, state, runtime_language, runtime_base_image, runtime_port, needs_db, container_id, public_url, created_at, updated_at, expires_at FROM sandboxes WHERE id = $1
`

func (q *Queries) GetSandboxByID(ctx context.Context, id uuid.UUID) (Sandbox, error) {
	row := q.db.QueryRow(ctx, getSandboxByID, id)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OwnerID,
		&i.Name,
		&i.GitUrl,
		&i.GitBranch,
		&i.State,
		&i.RuntimeLanguage,
		&i.RuntimeBaseImage,
		&i.RuntimePort,
		&i.NeedsDb,
		&i.ContainerID,
		&i.PublicUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, github_id, github_username, github_token_encrypted, avatar_url, max_sandboxes, max_builds_per_hour, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.GithubID,
		&i.GithubUsername,
		&i.GithubTokenEncrypted,
		&i.AvatarUrl,
		&i.MaxSandboxes,
		&i.MaxBuildsPerHour,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGithubID = `-- name: GetUserByGithubID :one
SELECT id, email, username, github_id, github_username, github_token_encrypted, avatar_url, max_sandboxes, max_builds_per_hour, created_at, updated_at FROM users WHERE github_id = $1
`

func (q *Queries) GetUserByGithubID(ctx context.Context, githubID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGithubID, githubID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.GithubID,
		&i.GithubUsername,
		&i.GithubTokenEncrypted,
		&i.AvatarUrl,
		&i.MaxSandboxes,
		&i.MaxBuildsPerHour,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username, github_id, github_username, github_token_encrypted, avatar_url, max_sandboxes, max_builds_per_hour, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.GithubID,
		&i.GithubUsername,
		&i.GithubTokenEncrypted,
		&i.AvatarUrl,
		&i.MaxSandboxes,
		&i.MaxBuildsPerHour,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSandboxesByProject = `-- name: ListSandboxesByProject :many
SELECT id, project_id, owner_id, name, git_url, git_branch, state, runtime_language, runtime_base_image, runtime_port, needs_db, container_id, public_url, created_at, updated_at, expires_at FROM sandboxes WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSandboxesByProject(ctx context.Context, projectID pgtype.UUID) ([]Sandbox, error) {
	rows, err := q.db.Query(ctx, listSandboxesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sandbox{}
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.OwnerID,
			&i.Name,
			&i.GitUrl,
			&i.GitBranch,
			&i.State,
			&i.RuntimeLanguage,
			&i.RuntimeBaseImage,
			&i.RuntimePort,
			&i.NeedsDb,
			&i.ContainerID,
			&i.PublicUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSandboxContainer = `-- name: UpdateSandboxContainer :exec
UPDATE sandboxes SET container_id = $2, public_url = $3, updated_at = NOW() WHERE id = $1
`

type UpdateSandboxContainerParams struct {
	ID          uuid.UUID   `json:"id"`
	ContainerID pgtype.Text `json:"container_id"`
	PublicUrl   pgtype.Text `json:"public_url"`
}

func (q *Queries) UpdateSandboxContainer(ctx context.Context, arg UpdateSandboxContainerParams) error {
	_, err := q.db.Exec(ctx, updateSandboxContainer, arg.ID, arg.ContainerID, arg.PublicUrl)
	return err
}

const updateSandboxState = `-- name: UpdateSandboxState :exec
UPDATE sandboxes SET state = $2, updated_at = NOW() WHERE id = $1
`

type UpdateSandboxStateParams struct {
	ID    uuid.UUID `json:"id"`
	State string    `json:"state"`
}

func (q *Queries) UpdateSandboxState(ctx context.Context, arg UpdateSandboxStateParams) error {
	_, err := q.db.Exec(ctx, updateSandboxState, arg.ID, arg.State)
	return err
}
