// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: share_link.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createShareLink = `-- name: CreateShareLink :one
INSERT INTO share_links (
    project_id, code, role, created_by, expires_at, max_uses
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, project_id, code, role, created_by, expires_at, max_uses, uses_count, created_at, revoked_at
`

type CreateShareLinkParams struct {
	ProjectID uuid.UUID          `json:"project_id"`
	Code      string             `json:"code"`
	Role      string             `json:"role"`
	CreatedBy uuid.UUID          `json:"created_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	MaxUses   pgtype.Int4        `json:"max_uses"`
}

func (q *Queries) CreateShareLink(ctx context.Context, arg CreateShareLinkParams) (ShareLink, error) {
	row := q.db.QueryRow(ctx, createShareLink,
		arg.ProjectID,
		arg.Code,
		arg.Role,
		arg.CreatedBy,
		arg.ExpiresAt,
		arg.MaxUses,
	)
	var i ShareLink
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Code,
		&i.Role,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UsesCount,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteShareLink = `-- name: DeleteShareLink :exec
DELETE FROM share_links WHERE id = $1
`

func (q *Queries) DeleteShareLink(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteShareLink, id)
	return err
}

const getShareLinkByCode = `-- name: GetShareLinkByCode :one
SELECT id, project_id, code, role, created_by, expires_at, max_uses, uses_count, created_at, revoked_at FROM share_links
WHERE code = $1 AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at > NOW())
AND (max_uses IS NULL OR uses_count < max_uses)
`

func (q *Queries) GetShareLinkByCode(ctx context.Context, code string) (ShareLink, error) {
	row := q.db.QueryRow(ctx, getShareLinkByCode, code)
	var i ShareLink
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Code,
		&i.Role,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UsesCount,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getShareLinkByID = `-- name: GetShareLinkByID :one
SELECT id, project_id, code, role, created_by, expires_at, max_uses, uses_count, created_at, revoked_at FROM share_links WHERE id = $1
`

func (q *Queries) GetShareLinkByID(ctx context.Context, id uuid.UUID) (ShareLink, error) {
	row := q.db.QueryRow(ctx, getShareLinkByID, id)
	var i ShareLink
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Code,
		&i.Role,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UsesCount,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getShareLinksByProject = `-- name: GetShareLinksByProject :many
SELECT id, project_id, code, role, created_by, expires_at, max_uses, uses_count, created_at, revoked_at FROM share_links
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetShareLinksByProject(ctx context.Context, projectID uuid.UUID) ([]ShareLink, error) {
	rows, err := q.db.Query(ctx, getShareLinksByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShareLink{}
	for rows.Next() {
		var i ShareLink
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Code,
			&i.Role,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.MaxUses,
			&i.UsesCount,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementShareLinkUses = `-- name: IncrementShareLinkUses :exec
UPDATE share_links SET uses_count = uses_count + 1 WHERE id = $1
`

func (q *Queries) IncrementShareLinkUses(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementShareLinkUses, id)
	return err
}

const updateShareLink = `-- name: UpdateShareLink :one
UPDATE share_links
SET uses_count = uses_count + 1,
    revoked_at = COALESCE($2, revoked_at)
WHERE id = $1
RETURNING id, project_id, code, role, created_by, expires_at, max_uses, uses_count, created_at, revoked_at
`

type UpdateShareLinkParams struct {
	ID        uuid.UUID          `json:"id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) UpdateShareLink(ctx context.Context, arg UpdateShareLinkParams) (ShareLink, error) {
	row := q.db.QueryRow(ctx, updateShareLink, arg.ID, arg.RevokedAt)
	var i ShareLink
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Code,
		&i.Role,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UsesCount,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}
