// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (id, email, username, github_id, github_username, avatar_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, username, github_id, github_username, github_token_encrypted, avatar_url, max_sandboxes, max_builds_per_hour, created_at, updated_at
`

type CreateUserParams struct {
	ID             uuid.UUID   `json:"id"`
	Email          string      `json:"email"`
	Username       pgtype.Text `json:"username"`
	GithubID       pgtype.Text `json:"github_id"`
	GithubUsername pgtype.Text `json:"github_username"`
	AvatarUrl      pgtype.Text `json:"avatar_url"`
}

// User queries.
//
// These lived in queries/sandbox.sql until the legacy sandbox model was
// removed, which meant deleting the sandbox queries silently deleted the user
// queries too. They are unrelated to sandboxes and belong here.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.GithubID,
		arg.GithubUsername,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.GithubID,
		&i.GithubUsername,
		&i.GithubTokenEncrypted,
		&i.AvatarUrl,
		&i.MaxSandboxes,
		&i.MaxBuildsPerHour,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, github_id, github_username, github_token_encrypted, avatar_url, max_sandboxes, max_builds_per_hour, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.GithubID,
		&i.GithubUsername,
		&i.GithubTokenEncrypted,
		&i.AvatarUrl,
		&i.MaxSandboxes,
		&i.MaxBuildsPerHour,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGithubID = `-- name: GetUserByGithubID :one
SELECT id, email, username, github_id, github_username, github_token_encrypted, avatar_url, max_sandboxes, max_builds_per_hour, created_at, updated_at FROM users WHERE github_id = $1
`

func (q *Queries) GetUserByGithubID(ctx context.Context, githubID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGithubID, githubID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.GithubID,
		&i.GithubUsername,
		&i.GithubTokenEncrypted,
		&i.AvatarUrl,
		&i.MaxSandboxes,
		&i.MaxBuildsPerHour,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username, github_id, github_username, github_token_encrypted, avatar_url, max_sandboxes, max_builds_per_hour, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.GithubID,
		&i.GithubUsername,
		&i.GithubTokenEncrypted,
		&i.AvatarUrl,
		&i.MaxSandboxes,
		&i.MaxBuildsPerHour,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
