// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workspace.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (
    project_id, name, type, base_workspace_id, owner_id, git_branch, git_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, project_id, name, type, base_workspace_id, owner_id, git_branch, commit_hash, has_uncommitted_changes, last_synced_at, created_at, updated_at, deleted_at, git_url
`

type CreateWorkspaceParams struct {
	ProjectID       uuid.UUID   `json:"project_id"`
	Name            string      `json:"name"`
	Type            string      `json:"type"`
	BaseWorkspaceID pgtype.UUID `json:"base_workspace_id"`
	OwnerID         uuid.UUID   `json:"owner_id"`
	GitBranch       string      `json:"git_branch"`
	GitUrl          string      `json:"git_url"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.ProjectID,
		arg.Name,
		arg.Type,
		arg.BaseWorkspaceID,
		arg.OwnerID,
		arg.GitBranch,
		arg.GitUrl,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Type,
		&i.BaseWorkspaceID,
		&i.OwnerID,
		&i.GitBranch,
		&i.CommitHash,
		&i.HasUncommittedChanges,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.GitUrl,
	)
	return i, err
}

const createWorkspaceMember = `-- name: CreateWorkspaceMember :one
INSERT INTO workspace_members (workspace_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (workspace_id, user_id) DO UPDATE SET role = EXCLUDED.role
RETURNING id, workspace_id, user_id, role, created_at
`

type CreateWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
}

func (q *Queries) CreateWorkspaceMember(ctx context.Context, arg CreateWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, createWorkspaceMember, arg.WorkspaceID, arg.UserID, arg.Role)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWorkspaceMember = `-- name: DeleteWorkspaceMember :exec
DELETE FROM workspace_members WHERE workspace_id = $1 AND user_id = $2
`

type DeleteWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteWorkspaceMember(ctx context.Context, arg DeleteWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceMember, arg.WorkspaceID, arg.UserID)
	return err
}

const getCanonicalWorkspace = `-- name: GetCanonicalWorkspace :one
SELECT id, project_id, name, type, base_workspace_id, owner_id, git_branch, commit_hash, has_uncommitted_changes, last_synced_at, created_at, updated_at, deleted_at, git_url FROM workspaces 
WHERE project_id = $1 AND type = 'CANONICAL' AND deleted_at IS NULL
`

func (q *Queries) GetCanonicalWorkspace(ctx context.Context, projectID uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getCanonicalWorkspace, projectID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Type,
		&i.BaseWorkspaceID,
		&i.OwnerID,
		&i.GitBranch,
		&i.CommitHash,
		&i.HasUncommittedChanges,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.GitUrl,
	)
	return i, err
}

const getForkWorkspaces = `-- name: GetForkWorkspaces :many
SELECT id, project_id, name, type, base_workspace_id, owner_id, git_branch, commit_hash, has_uncommitted_changes, last_synced_at, created_at, updated_at, deleted_at, git_url FROM workspaces 
WHERE base_workspace_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetForkWorkspaces(ctx context.Context, baseWorkspaceID pgtype.UUID) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, getForkWorkspaces, baseWorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Type,
			&i.BaseWorkspaceID,
			&i.OwnerID,
			&i.GitBranch,
			&i.CommitHash,
			&i.HasUncommittedChanges,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.GitUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserWorkspaces = `-- name: GetUserWorkspaces :many
SELECT w.id, w.project_id, w.name, w.type, w.base_workspace_id, w.owner_id, w.git_branch, w.commit_hash, w.has_uncommitted_changes, w.last_synced_at, w.created_at, w.updated_at, w.deleted_at, w.git_url, wm.role as member_role
FROM workspaces w
JOIN workspace_members wm ON w.id = wm.workspace_id
WHERE wm.user_id = $1 AND w.deleted_at IS NULL
ORDER BY w.updated_at DESC
`

type GetUserWorkspacesRow struct {
	ID                    uuid.UUID          `json:"id"`
	ProjectID             uuid.UUID          `json:"project_id"`
	Name                  string             `json:"name"`
	Type                  string             `json:"type"`
	BaseWorkspaceID       pgtype.UUID        `json:"base_workspace_id"`
	OwnerID               uuid.UUID          `json:"owner_id"`
	GitBranch             string             `json:"git_branch"`
	CommitHash            pgtype.Text        `json:"commit_hash"`
	HasUncommittedChanges pgtype.Bool        `json:"has_uncommitted_changes"`
	LastSyncedAt          pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
	GitUrl                string             `json:"git_url"`
	MemberRole            string             `json:"member_role"`
}

func (q *Queries) GetUserWorkspaces(ctx context.Context, userID uuid.UUID) ([]GetUserWorkspacesRow, error) {
	rows, err := q.db.Query(ctx, getUserWorkspaces, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserWorkspacesRow{}
	for rows.Next() {
		var i GetUserWorkspacesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Type,
			&i.BaseWorkspaceID,
			&i.OwnerID,
			&i.GitBranch,
			&i.CommitHash,
			&i.HasUncommittedChanges,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.GitUrl,
			&i.MemberRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, project_id, name, type, base_workspace_id, owner_id, git_branch, commit_hash, has_uncommitted_changes, last_synced_at, created_at, updated_at, deleted_at, git_url FROM workspaces WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Type,
		&i.BaseWorkspaceID,
		&i.OwnerID,
		&i.GitBranch,
		&i.CommitHash,
		&i.HasUncommittedChanges,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.GitUrl,
	)
	return i, err
}

const getWorkspaceMember = `-- name: GetWorkspaceMember :one
SELECT wm.id, wm.workspace_id, wm.user_id, wm.role, wm.created_at, u.username, u.email, u.avatar_url
FROM workspace_members wm
JOIN users u ON wm.user_id = u.id
WHERE wm.workspace_id = $1 AND wm.user_id = $2
`

type GetWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

type GetWorkspaceMemberRow struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Username    pgtype.Text        `json:"username"`
	Email       string             `json:"email"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (GetWorkspaceMemberRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var i GetWorkspaceMemberRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.Username,
		&i.Email,
		&i.AvatarUrl,
	)
	return i, err
}

const getWorkspaceMembers = `-- name: GetWorkspaceMembers :many
SELECT wm.id, wm.workspace_id, wm.user_id, wm.role, wm.created_at, u.username, u.email, u.avatar_url
FROM workspace_members wm
JOIN users u ON wm.user_id = u.id
WHERE wm.workspace_id = $1
ORDER BY 
    CASE wm.role WHEN 'OWNER' THEN 0 WHEN 'EDITOR' THEN 1 ELSE 2 END,
    wm.created_at
`

type GetWorkspaceMembersRow struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Username    pgtype.Text        `json:"username"`
	Email       string             `json:"email"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) GetWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) ([]GetWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, getWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWorkspaceMembersRow{}
	for rows.Next() {
		var i GetWorkspaceMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Username,
			&i.Email,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceMembersByUser = `-- name: GetWorkspaceMembersByUser :many
SELECT wm.id, wm.workspace_id, wm.user_id, wm.role, wm.created_at, u.username, u.email, u.avatar_url
FROM workspace_members wm
JOIN users u ON wm.user_id = u.id
WHERE wm.user_id = $1
ORDER BY wm.created_at
`

type GetWorkspaceMembersByUserRow struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Username    pgtype.Text        `json:"username"`
	Email       string             `json:"email"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) GetWorkspaceMembersByUser(ctx context.Context, userID uuid.UUID) ([]GetWorkspaceMembersByUserRow, error) {
	rows, err := q.db.Query(ctx, getWorkspaceMembersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWorkspaceMembersByUserRow{}
	for rows.Next() {
		var i GetWorkspaceMembersByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Username,
			&i.Email,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspacesByProject = `-- name: GetWorkspacesByProject :many
SELECT id, project_id, name, type, base_workspace_id, owner_id, git_branch, commit_hash, has_uncommitted_changes, last_synced_at, created_at, updated_at, deleted_at, git_url FROM workspaces 
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY 
    CASE type WHEN 'CANONICAL' THEN 0 ELSE 1 END,
    created_at DESC
`

func (q *Queries) GetWorkspacesByProject(ctx context.Context, projectID uuid.UUID) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, getWorkspacesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Type,
			&i.BaseWorkspaceID,
			&i.OwnerID,
			&i.GitBranch,
			&i.CommitHash,
			&i.HasUncommittedChanges,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.GitUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWorkspace = `-- name: SoftDeleteWorkspace :exec
UPDATE workspaces SET deleted_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteWorkspace(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteWorkspace, id)
	return err
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces SET
    name = COALESCE($2, name),
    git_branch = COALESCE($3, git_branch),
    commit_hash = COALESCE($4, commit_hash),
    has_uncommitted_changes = COALESCE($5, has_uncommitted_changes),
    last_synced_at = COALESCE($6, last_synced_at),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_id, name, type, base_workspace_id, owner_id, git_branch, commit_hash, has_uncommitted_changes, last_synced_at, created_at, updated_at, deleted_at, git_url
`

type UpdateWorkspaceParams struct {
	ID                    uuid.UUID          `json:"id"`
	Name                  pgtype.Text        `json:"name"`
	GitBranch             pgtype.Text        `json:"git_branch"`
	CommitHash            pgtype.Text        `json:"commit_hash"`
	HasUncommittedChanges pgtype.Bool        `json:"has_uncommitted_changes"`
	LastSyncedAt          pgtype.Timestamptz `json:"last_synced_at"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspace,
		arg.ID,
		arg.Name,
		arg.GitBranch,
		arg.CommitHash,
		arg.HasUncommittedChanges,
		arg.LastSyncedAt,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Type,
		&i.BaseWorkspaceID,
		&i.OwnerID,
		&i.GitBranch,
		&i.CommitHash,
		&i.HasUncommittedChanges,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.GitUrl,
	)
	return i, err
}

const updateWorkspaceMember = `-- name: UpdateWorkspaceMember :one
UPDATE workspace_members SET role = $3 WHERE workspace_id = $1 AND user_id = $2 RETURNING id, workspace_id, user_id, role, created_at
`

type UpdateWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
}

func (q *Queries) UpdateWorkspaceMember(ctx context.Context, arg UpdateWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceMember, arg.WorkspaceID, arg.UserID, arg.Role)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
